const D=window.STUDY_DATA; const $=s=>document.querySelector(s);
let progress=JSON.parse(localStorage.getItem("aplusProgress")||"{}");
let recallState=JSON.parse(localStorage.getItem("aplusRecall")||"{}");
function save(){localStorage.setItem("aplusProgress",JSON.stringify(progress));renderProgress();updateMastered()}
function saveRecall(){localStorage.setItem("aplusRecall",JSON.stringify(recallState));renderProgress()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active");if(b.dataset.view==="progress")renderProgress();if(b.dataset.view==="recall")loadRecall()});
function renderModules(){let q=$("#search").value.toLowerCase(),f=$("#coreFilter").value;$("#moduleGrid").innerHTML=D.modules.filter(m=>(f==="All"||m.core===f)&&(`${m.title} ${m.domain} ${m.topics.join(" ")}`.toLowerCase().includes(q))).map(m=>`<article class="module"><span class="core">${m.core} • MODULE ${m.num}</span><h3>${m.title}</h3><p>${m.domain}</p><ul>${m.topics.map(t=>`<li>${t}</li>`).join("")}</ul><button onclick="startModule(${m.num})">Study module</button></article>`).join("")}
$("#search").oninput=renderModules;$("#coreFilter").onchange=renderModules;
function opts(id){$(id).innerHTML='<option value="all">All modules</option>'+D.modules.map(m=>`<option value="${m.num}">Module ${m.num}: ${m.title}</option>`).join("")} opts("#cardModule");opts("#quizModule");opts("#recallModule");
let deck=[],ci=0;function loadDeck(){let v=$("#cardModule").value;deck=D.cards.filter(c=>v==="all"||c.module==v);ci=0;showCard()}function showCard(){if(!deck.length)return;let c=deck[ci%deck.length];$("#flashcard").classList.remove("flipped");$("#cardQ").textContent=c.q;$("#cardA").textContent=c.a;$("#cardCount").textContent=`${ci%deck.length+1} / ${deck.length}`;$("#know").dataset.key=`${c.module}|${c.q}`}
$("#cardModule").onchange=loadDeck;$("#flashcard").onclick=()=>$("#flashcard").classList.toggle("flipped");$("#again").onclick=()=>{ci++;showCard()};$("#know").onclick=()=>{progress[$("#know").dataset.key]=1;save();ci++;showCard()};
window.startModule=n=>{document.querySelector('[data-view="cards"]').click();$("#cardModule").value=n;loadDeck()}
let quiz=[],qi=0,correct=0,total=0,answered=false;function makeQuiz(){let v=$("#quizModule").value;quiz=D.cards.filter(c=>v==="all"||c.module==v);qi=Math.floor(Math.random()*quiz.length);showQuiz()}
function showQuiz(){answered=false;let c=quiz[qi];$("#quizQ").textContent=c.q;$("#feedback").textContent="";let wrong=D.cards.filter(x=>x.a!==c.a).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.a);let arr=[c.a,...wrong].sort(()=>Math.random()-.5);$("#choices").innerHTML=arr.map(a=>`<button class="choice">${a}</button>`).join("");document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>answer(b,c.a))}
function answer(b,a){if(answered)return;answered=true;total++;if(b.textContent===a){correct++;b.classList.add("correct");$("#feedback").textContent="Correct."}else{b.classList.add("wrong");[...document.querySelectorAll(".choice")].find(x=>x.textContent===a)?.classList.add("correct");$("#feedback").textContent="Not quite — review the correct answer."}$("#score").textContent=`Score: ${correct} / ${total}`}
$("#nextQ").onclick=()=>{qi=Math.floor(Math.random()*quiz.length);showQuiz()};$("#quizModule").onchange=makeQuiz;
function cardKey(c){return `${c.module}|${c.q}`}
function recallPool(){let v=$("#recallModule").value,now=Date.now();let pool=D.cards.filter(c=>v==="all"||c.module==v);let due=pool.filter(c=>!recallState[cardKey(c)]||recallState[cardKey(c)].due<=now);return due.length?due.sort((a,b)=>(recallState[cardKey(a)]?.due||0)-(recallState[cardKey(b)]?.due||0)):pool.sort((a,b)=>(recallState[cardKey(a)]?.due||0)-(recallState[cardKey(b)]?.due||0)).slice(0,1)}
let recallCard=null;
function loadRecall(){let pool=recallPool();recallCard=pool[0];if(!recallCard){$("#recallQ").textContent="No recall cards available.";return}let v=$("#recallModule").value,all=D.cards.filter(c=>v==="all"||c.module==v),now=Date.now(),due=all.filter(c=>!recallState[cardKey(c)]||recallState[cardKey(c)].due<=now).length;$("#dueCount").textContent=`${due} due now`;$("#recallTag").textContent=`Module ${recallCard.module} • ${recallCard.domain}`;$("#recallQ").textContent=recallCard.q;$("#recallA").textContent=recallCard.a;$("#recallAnswer").value="";$("#recallAnswer").disabled=false;$("#recallKey").classList.add("hidden");$("#revealRecall").classList.remove("hidden")}
$("#recallModule").onchange=loadRecall;$("#revealRecall").onclick=()=>{$("#recallKey").classList.remove("hidden");$("#revealRecall").classList.add("hidden");$("#recallAnswer").disabled=true};
document.querySelectorAll(".rating button").forEach(b=>b.onclick=()=>{if(!recallCard)return;let key=cardKey(recallCard),old=recallState[key]||{level:0,reps:0};let rate=b.dataset.rate,days=0,level=old.level||0;if(rate==="again"){level=0;days=0}else if(rate==="hard"){level=Math.max(1,level);days=1}else if(rate==="good"){level++;days=[0,1,3,7,14,30,60][Math.min(level,6)]}else{level+=2;days=[0,1,3,7,14,30,60][Math.min(level,6)]}recallState[key]={level,reps:(old.reps||0)+1,last:Date.now(),rating:rate,due:Date.now()+days*86400000};if(rate==="good"||rate==="easy")progress[key]=1;saveRecall();save();loadRecall()});
function renderProgress(){let rows=D.modules.map(m=>{let cs=D.cards.filter(c=>c.module===m.num),k=cs.filter(c=>progress[cardKey(c)]).length,p=Math.round(k/cs.length*100),r=cs.filter(c=>(recallState[cardKey(c)]?.reps||0)>0).length;return `<div class="prow"><div class="prowTop"><span>Module ${m.num}: ${m.domain}</span><b>${k}/${cs.length} mastered • ${r} recalled</b></div><div class="bar"><div class="fill" style="width:${p}%"></div></div></div>`}).join("");$("#progressRows").innerHTML=rows}
function updateMastered(){$("#mastered").textContent=Object.keys(progress).length}$("#reset").onclick=()=>{if(confirm("Reset all saved study and recall progress?")){progress={};recallState={};localStorage.removeItem("aplusRecall");saveRecall();save()}}
renderModules();loadDeck();makeQuiz();renderProgress();updateMastered();loadRecall();
const APP_VERSION="0.3";let testerId=localStorage.getItem("aplusTesterId");if(!testerId){testerId="T-"+Math.random().toString(36).slice(2,8).toUpperCase();localStorage.setItem("aplusTesterId",testerId)}document.querySelector("#testerLabel").textContent=`Alpha ${APP_VERSION} • Tester ${testerId}`;const fm=document.querySelector("#feedbackModal"),fb=document.querySelector("#feedbackBtn");fb.onclick=()=>fm.classList.remove("hidden");document.querySelector("#closeFeedback").onclick=()=>fm.classList.add("hidden");fm.onclick=e=>{if(e.target===fm)fm.classList.add("hidden")};function feedbackItems(){return JSON.parse(localStorage.getItem("aplusFeedback")||"[]")}document.querySelector("#saveFeedback").onclick=()=>{const text=document.querySelector("#feedbackText").value.trim();if(!text){document.querySelector("#feedbackStatus").textContent="Please enter feedback first.";return}const items=feedbackItems();items.push({testerId,version:APP_VERSION,timestamp:new Date().toISOString(),category:document.querySelector("#feedbackCategory").value,view:[...document.querySelectorAll(".view")].find(v=>v.classList.contains("active"))?.id||"unknown",text});localStorage.setItem("aplusFeedback",JSON.stringify(items));document.querySelector("#feedbackText").value="";document.querySelector("#feedbackStatus").textContent=`Saved locally. ${items.length} feedback item(s) ready to export.`};document.querySelector("#exportFeedback").onclick=()=>{const items=feedbackItems();if(!items.length){document.querySelector("#feedbackStatus").textContent="No saved feedback yet.";return}const payload={app:"A+ Study Deck",version:APP_VERSION,testerId,exportedAt:new Date().toISOString(),feedback:items};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`aplus-alpha-feedback-${testerId}.json`;a.click();URL.revokeObjectURL(a.href)};